### ISSUE TITLE
Layihe deyerlendirme

### ISSUE THREAD

**Issue by Aytac11** [NargizHasanova/PragmatechFoundationProject#1]
header-icons-larda cursor pointer olmalidir
row strukturun sehvdir.
row-nu 2 dene col-6 ya bolmelisen. Sonra hemin col-6 lari yeniden 2 cola bolmelisen- bunlardan biri imageni digeri contenti saxlasin deye. Basa dusmesen xeber edersen yeniden anladaram.

Lahiyede cox az is gorulub.

**Comment by NargizHasanova** [comment]
dediklerini duzeltdim.Layihenin ana seyfesinide bitirdim.Xahis edirem imkan olanda bir daha baxasiz
